### ISSUE TITLE
Remove error for vector component being bigger than 1/ smaller -1

### ISSUE THREAD

**Issue by kurz-m** [kurz-m/miniRT#17]
https://github.com/kurz-m/miniRT/blob/01eaa0b68f92f26c2e7004fc0744bf3e766acaf7/parser.c#L29-L32

Because we are already taking the norm vector from the vector we are getting as input for the direction of an object, we should not give out an error when there is a component of a vector bigger than 1 or smaller than -1

**Comment by flolau2k** [comment]
Fixed in fe5e8eb081903b1b75bdee6ce711227e0ea86a8a
Didn't remove the boundary cheching in parse_double completely because it is used in Sphere and Cylinder to check that the Diameter is positive.

**Comment by kurz-m** [comment]
Seems legit. Nice fix! 💯
